### ISSUE TITLE
Improve private messages.... But how?

### ISSUE THREAD

**Issue by jD91mZM2** [synac-chat/server#4]
The current way is certainly the easiest and cleanest. Just forward a bunch of bytes from one user to another. The client takes care of E2E encryption completely.

Problem: As well as having least amount of code, this approach is also the least powerful.

Possible solutions:
 - Implement more functions for private messages. This quickly becomes an entire copy of the channels, which means a lot of similar code. I really don't like this approach.
 - Make everything a channel. Hardcoded channel #pm (channels can have duplicate names) makes sender and recipient have read and write access and leaves everyone else with 0 permissions. Problem is that this is quite hacky, and introduces a difficulty finding out who is the recipient (loop through users and check who has acess). As well as that, providing access for anybody to create a channel is... perhaps not a good idea.

**Comment by jD91mZM2** [comment]
I've been thinking. If you look specifically at Steam's chat, it's almost exactly as powerful as synac's current private messages. Can't edit. Can't delete. Can't see message history. IRC also reminds of that. As well as those, Twitter also can't edit shit.

Clearly users don't seem to mind. Perhaps we should let it be as depowered as it is?

**Comment by Mnpn** [comment]
Just because others aren't innovating doesn't mean you shouldn't either.
Message editing is a nice bonus, and while people don't complain about Twitter's lack of message editing they do complain about the lack of Tweet editing.

**Comment by jD91mZM2** [comment]
Yeah but if people want more features they can just ask the server owner to create a nice little private channel for them

**Comment by Mnpn** [comment]
Which shouldn't be necessary and is just another extra step.

**Comment by jD91mZM2** [comment]
Most people won't use private messages. Most people won't mind. Probably a very little amount of them would care. Unless we can find a way for private messages that doesn't involve copy pasting huge chunks of code and making everything messy AF, this is the cleanest and simpilest solution.

**Comment by Mnpn** [comment]
Find a way to make it less messy then? lol. "Most people won't use Tweet editing, so we won't add it"
I do mind thanks, pls add

**Comment by jD91mZM2** [comment]
> Find a way to make it less messy then?

Want me to keep this issue open until I die of old age?

**Comment by jD91mZM2** [comment]
The least messy way I can see would be the second approach I mentioned. But that is really hacky and if you ever tell anybody you used that solution they will ask what the fsck is wrong with you. Hardcoding channel names, making it public who talked to who, looping through users to find the recipient, et.c.

**Comment by Mnpn** [comment]
How about just making DMs like permanent servers except they just have channels names after the people who they can talk to?

**Comment by jD91mZM2** [comment]
Still hardcoded. Can still see who talked with who. Also, users aren't shared across servers.  
Perhaps an optional server with a bot that creates channels for people who ask. Then that's possible.

**Comment by jD91mZM2** [comment]
Perhaps an optional server with a bot that creates channels for people who asks. Then that's possible.

**Comment by jD91mZM2** [comment]
Idea: Every messages in any channel gets an optional `recipients` value.
Problem: Since messages would then be all over the place, end-to-end encryption would be difficult.
