### ISSUE TITLE
Private message encryption is horrible

### ISSUE THREAD

**Issue by jD91mZM2** [synac-chat/server#7]
- Not forward proof (I should use diffie-hellman)
 - Using AES EBC [which is bad](https://crypto.stackexchange.com/questions/20941/why-shouldnt-i-use-ecb-encryption)

Technically this isn't a server issue, but I put issues related to the protocol itself here.

**Comment by jD91mZM2** [comment]
The problem with diffie-hellman is that it requires a whole exchange first.  
Also private mesages are underpowered either way.  
Should we just remove them?

**Comment by ttofis** [comment]
Yeah sure.... They can go. I am really neutral on this because Private Messages are an important thing, but I guess rn anyways they are too underpowered to have a real feature. If somebody wants to pm, they can run a small server real quick and do it, despite it will require port forwarding to do something like this. But yeah I am not happy to let them go.

**Comment by jD91mZM2** [comment]
@Mnpn03 had the idea that we should make a server that lets you create a private channel with whoever using a bot.

**Comment by ttofis** [comment]
the server owner couldn't read the messages?

**Comment by jD91mZM2** [comment]
Sadly, yes they could. But the bot could always be open source ¯\\\_(ツ)_/¯

**Comment by jD91mZM2** [comment]
IDEA! We abandon private messaging. This can be done using one official and optionally also self-hosted PM servers.
We do another spin-off of the original plan (which was to E2E encrypt any message):
Allowing any message to be encrypted using AES with a custom password. This password would somehow (using another synac server, another service all together, irl or whatever) be sent to all the recipients, which can later right click the message and decrypt it.

Thoughts?

**Comment by tbodt** [comment]
Making private messaging really secure is *really hard*. Take a look at signal, they solved the problem and they have libraries for doing it. The C library shouldn't be hard to use from Rust. https://github.com/WhisperSystems/libsignal-protocol-c

**Comment by jD91mZM2** [comment]
Well we still have #4 making private messages bad for other reasons.  
Btw, has signal been security audited?

**Comment by tbodt** [comment]
Very

**Comment by tbodt** [comment]
https://eprint.iacr.org/2016/1013.pdf

**Comment by jD91mZM2** [comment]
Alright, I tried my best to understand how to actually use libsignal. It's all very confusing with the registration ids, prekeys, identity key pair, and all that.
First of all, there is a signal library for Rust, but it's not on crates.io, and it's merely the pure C bindings.
Second of all, `session_builder_create` seems to take a phone number.
Third of all, the protocol seems to require some exchanges, just like diffie-hellman, which means I'd have to have a system and packets for that.

I beg for mercey.

**Comment by jD91mZM2** [comment]
No encryption at all in the latest PM changes. If users need security they should just self-host either way. Although, this might get changed in the future.

**Comment by ttofis** [comment]
If you open the database you can see the pms?

**Comment by jD91mZM2** [comment]
Yes. Like I said, this might get changed in the future. But if users *really* want security they should just self-host either way.
